#! perl
#-*-encoding:utf-8-*-
# urxvt 插件实现被选单词的快速翻译
# from  http://linuxtoy.org/archives/urxvt-插件实现被选单词的快速翻译.html

sub onstart {
	my ($self) = @;
	$self->grab_button (3, urxvt::ControlMask);
	()
}

sub onbuttonpress {
	my ($self, $event) = @_;
	if ($event-&gt;{button} == 3) {
		my $popup = $self-&gt;popup ($event)
			or return 1;

		my ($word) = $self-&gt;selection =~ m/([a-zA-Z]+)/;

		open PIPE, "export LANG=zh_CN.UTF-8; /usr/bin/sdcv -n --utf8-output -u 'XDICT英汉辞典' '$word' | tail -n +5 | head -15 | head -n -1 |"
			or close PIPE;

		for my $eachline (&lt;PIPE&gt;) {
			chomp $eachline;
			$eachline = $self-&gt;locale_decode($eachline);
			$popup-&gt;add_title ($eachline);
		}
		close PIPE;

		$popup-&gt;show;
	}

	()
}
